### PR TITLE
Add prettier

### LINKED ISSUE #37: Set up Prettier (and maybe eslint)
Prettier will make the code look consistent and we can enforce semicolons or double/one quote(s) and it will make a much more even codebase. Also, when you format the file, less merge conflicts will happen. ESLint, if you really want to be strict, will allow us to enforce the Prettier rules to make a much more even codebase. I can try to make this if you would like.

### PR DESCRIPTION
**Pull request by webdev03**
In `app/` then there is `.prettierconfig.json` see https://prettier.io/docs/en/configuration.html how to edit it
Closes #37 (oops I earlier said 25)

### CODE REVIEW

**Review by hello-smile6 — APPROVED** [review]
Great! Could you make a PR on my fork?

**Comment by webdev03** [comment]
@hello-smile6 With what?

**Comment by hello-smile6** [comment]
> @hello-smile6 With what?

With this.

**Review by hello-smile6 — CHANGES_REQUESTED** [review]
Leave the instructions!

**Comment by webdev03** [comment]
> Leave the instructions!

why?? its good for newcomers

**Review by hello-smile6 — APPROVED** [review]
Good idea.

**Comment by webdev03** [comment]
@JaydenDev before closing, tell me if you want github actions for checking if prettier was used, I can do it

**Review by hello-smile6 — APPROVED** [review]
Great! Could I have this?

**Comment by hello-smile6** [comment]
> Great! Could I have this?

Please?

**Comment by webdev03** [comment]
@hello-smile6 I did, now no more off-topic I think

**Comment by webdev03** [comment]
Please squash and merge when doing this, I have a lot of commits since with the help of hello-smile I am testing this

**Comment by webdev03** [comment]
@JaydenDev do you still think it is bloat?

**Comment by hello-smile6** [comment]
> @JaydenDev do you still think it is bloat?

I don't. And forks exist for a reason.

**Comment by JaydenDev** [comment]
bloat, bloat, bloat!

**Comment by webdev03** [comment]
It is NOT bloat! It adds NOTHING to the release of Freecat! It will make the styling more consistent! @JaydenDev please reconsider!

**Comment by JaydenDev** [comment]
Forcing the use of a utility is against what FreeCat stands for.

**Comment by webdev03** [comment]
Don't we force NodeJS and Electron? Sorry...

**Comment by JaydenDev** [comment]
I'd prefer if the prettier config was in config/

**Comment by webdev03** [comment]
`config/` is for the config of Freecat, not development I believe, isn't that a part of the source code? Prettier I think helps the source code to not become too different.

**Comment by JaydenDev** [comment]
i'm trusting this one...

**Pull request closed without merging**
