### PR TITLE
Bring freecat features into 2021

### PR DESCRIPTION
**Pull request by hello-smile6**
# Features added:

- [x] Reload button
- [x] Back button
- [x] Forward button
- [x] Settings
- [x] Settings button
- [x] Search from URL bar
- [x] Custom search provider

### CODE REVIEW

**Comment by JaydenDev** [comment]
you brought all the testing commits again..

**Comment by JaydenDev** [comment]
i'll manually apply each commit myself i guess

**Comment by hello-smile6** [comment]
> i'll manually apply each commit myself i guess

I didn't bring them. This is from the testing branch.

**Comment by JaydenDev** [comment]
the testing branch is broken... remember?

**Comment by hello-smile6** [comment]
See?
image

**Comment by hello-smile6** [comment]
> the testing branch is broken... remember?

I'll build, just to test.

**Comment by JaydenDev** [comment]
it is broken the stupid white screen
please redo your entire PR but the main branch as the base

**Comment by hello-smile6** [comment]
> it is broken the stupid white screen please redo your entire PR but the main branch as the base

Okay, will do.

**Comment by JaydenDev** [comment]
the testing branch is broken and obsolete dont use it

**Comment by JaydenDev** [comment]
I gotta go i'll merge the PR tomarrow assuming you'll have it remade with the main branch as the base

**Comment by hello-smile6** [comment]
> I gotta go i'll merge the PR tomarrow assuming you'll have it remade with the main branch as the base

Already got it.

**Pull request merged**
