### PR TITLE
Remove conflict markers, consolidate license

### PR DESCRIPTION
**Pull request by hello-smile6**

### CODE REVIEW

**Comment by JaydenDev** [comment]
Your PR will be reviewed over the next 24 hours.
Please continue to thoroughly test your code.
make sure its based off main, and up to date

**Comment by hello-smile6** [comment]
> Your PR will be reviewed over the next 24 hours. Please continue to thoroughly test your code. make sure its based off main, and up to date

I've tested, and it works.

**Comment by JaydenDev** [comment]
> > Your PR will be reviewed over the next 24 hours. Please continue to thoroughly test your code. make sure its based off main, and up to date
> 
> I've tested, and it works.

24 hour review will still continue

**Comment by hello-smile6** [comment]
> > > Your PR will be reviewed over the next 24 hours. Please continue to thoroughly test your code. make sure its based off main, and up to date
> > 
> > 
> > I've tested, and it works.
> 
> 24 hour review will still continue

Fine. Say bye to my changes.

**Comment by JaydenDev** [comment]
Moving to Catalyst anyway...

**Pull request closed without merging**
