### PR TITLE
Fix format.yml

### PR DESCRIPTION
**Pull request by kccuber-scratch**
The prettier action has indenting errors so I hope this fixes it...

### CODE REVIEW

**Comment by hello-smile6** [comment]
Run prettier

**Comment by kccuber-scratch** [comment]
Um oh it looks like pretter is just not installed in the code

**Comment by hello-smile6** [comment]
> Um oh it looks like pretter is just not installed in the code

Undo the nuke commit.

**Comment by hello-smile6** [comment]
Could someone add `<input>` support for https://github.com/MystPi/dreamcss ? @JaydenDev @webdev03 @ScolderCreations @ninjamar @kccuber-scratch

**Comment by webdev03** [comment]
@hello-smile6 I'm not contributing to freecat

**Comment by hello-smile6** [comment]
> @hello-smile6 I'm not contributing to freecat

Sorry I added you

**Pull request merged**
