### PR TITLE
better installation + running again

### PR DESCRIPTION
**Pull request by ninjamar**
i added better installation + running again again
can i get edit access to this repo?

### CODE REVIEW

**Review by hello-smile6 — APPROVED** [review]
Thanks for catching that!

**Comment by JaydenDev** [comment]
freecat has already been fixed.

**Comment by hello-smile6** [comment]
I'll run prettier and push, just to clean it up.

**Comment by hello-smile6** [comment]
> I'll run prettier and push, just to clean it up.

Done in fadd97840a62f805e968e098d20729cb9729b10f

**Comment by webdev03** [comment]
_offtopic_ I'm glad that people like the prettier setup!

**Comment by hello-smile6** [comment]
> _offtopic_ I'm glad that people like the prettier setup!

I agree.

**Pull request merged**
