### PR TITLE
Repo sync

### PR DESCRIPTION
**Pull request by hello-smile6**
I have tested locally.

### CODE REVIEW

**Comment by webdev03** [comment]
Hey, the actions workflow hasn't been tested and is in beta

**Comment by hello-smile6** [comment]
> Hey, the actions workflow hasn't been tested and is in beta

Then let's make it a draft PR.

**Comment by JaydenDev** [comment]
what is "repo sync"

**Comment by webdev03** [comment]
Adds the changes in hello-smile6 fork to this repository.

**Comment by JaydenDev** [comment]
webload.html was renamed to index.html a while back

**Comment by hello-smile6** [comment]
> webload.html was renamed to index.html a while back

Okay, I'll fix that.

**Comment by JaydenDev** [comment]
a check has failed. try running 'npm run check' in your code and run the formatter commands

**Comment by JaydenDev** [comment]
please remove anything related to moving all the code to /, as I have already sorted out the problem.

**Comment by JaydenDev** [comment]
all the changes of this PR have since already been applied, closing.

**Comment by hello-smile6** [comment]
> please remove anything related to moving all the code to /, as I have already sorted out the problem.

Okay, I merged that. There's no changes. I'll format it.

**Comment by webdev03** [comment]
> a check has failed. try running 'npm run check' in your code and run the formatter commands

It was because you didn't change the CI to fit changing the package.json, my PR does that.

**Comment by hello-smile6** [comment]
> all the changes of this PR have since already been applied, closing.

Actually, they have not. Look again.

**Comment by JaydenDev** [comment]
this better not break anything...

**Comment by JaydenDev** [comment]
conflicts...

**Comment by webdev03** [comment]
Which conflicts?

**Comment by JaydenDev** [comment]
app/package-lock.json
app/package.json

**Comment by webdev03** [comment]
> app/package-lock.json app/package.json

I can't see them as I am not @hello-smile6 or @JaydenDev unfortunately.

**Comment by JaydenDev** [comment]
i never gave hello-smile6 any special permissions...

**Comment by webdev03** [comment]
@hello-smile6 made this PR.

**Comment by webdev03** [comment]
Woohooo!

**Comment by hello-smile6** [comment]
Fixed.

**Comment by ninjamar** [comment]
Can you add me into the contributors section? I just had a PR that got merged (#45 )

**Comment by JaydenDev** [comment]
added you as a collaborator, accept the invite and see if that helps

**Comment by hello-smile6** [comment]
I'll fix it!

**Comment by webdev03** [comment]
Checks failed!

**Comment by ninjamar** [comment]
> added you as a collaborator, accept the invite and see if that helps

i don't see an invite

**Pull request merged**
