### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by hello-smile6**
This has been needed for a while.

### CODE REVIEW

**Comment by MystPi** [comment]
Why not use an MIT license?

**Comment by hello-smile6** [comment]
> Why not use an MIT license? GNU is a good license, but most open source software use MIT.

GPLv3 actually does something. The MIT license just says that people can't use things without giving credit. GPLv3 gives us source code, so people can't just start distributing a copy with malware. By using GPLv3, we'll always have source code.

**Comment by MystPi** [comment]
> > Why not use an MIT license? GNU is a good license, but most open source software use MIT.
> 
> GPLv3 actually does something. The MIT license just says that people can't use things without giving credit. GPLv3 gives us source code, so people can't just start distributing a copy with malware. By using GPLv3, we'll always have source code.

But FreeCat is free as in freedom, which means users should be able to do what they want with the source code.

**Comment by hello-smile6** [comment]
> > > Why not use an MIT license? GNU is a good license, but most open source software use MIT.
> > 
> > 
> > GPLv3 actually does something. The MIT license just says that people can't use things without giving credit. GPLv3 gives us source code, so people can't just start distributing a copy with malware. By using GPLv3, we'll always have source code.
> 
> But FreeCat is free as in freedom, which means users should be able to do what they want with the source code.

Yes. With GPL, they can do anything, provided they do the right thing and let others have their source. If they don't want to give us source, they can just keep their version private.

**Comment by hello-smile6** [comment]
> doesn't this have a license already?

No license file yet.

**Comment by MystPi** [comment]
Actually, it does have a license:
https://github.com/JaydenDev/freecat/blob/main/app/LICENSE.md

**Comment by JaydenDev** [comment]
LICENSE.md in app/
I'll accept the PR though.

**Comment by MystPi** [comment]
> LICENSE.md in app/ I'll accept the PR though.

Wait, then it will have two different types of licenses! CC0 and GPLv3.

**Comment by hello-smile6** [comment]
> > LICENSE.md in app/ I'll accept the PR though.
> 
> Wait, then it will have two different types of licenses! CC0 and GPLv3. I'd suggest removing one of them.

On it.

**Comment by hello-smile6** [comment]
> > LICENSE.md in app/ I'll accept the PR though.
> 
> Wait, then it will have two different types of licenses! CC0 and GPLv3. I'd suggest removing one of them.

@JaydenDev did it in https://github.com/JaydenDev/freecat/commit/6136909b08d08397fa4db8e3b808579591b601da

**Pull request merged**
