### PR TITLE
Add part of the code to make homepage not show URL, merge URL bar auto-update into testing

### PR DESCRIPTION
**Pull request by hello-smile6**
I couldn't figure out why the URL bar wasn't working! Now it will.

### CODE REVIEW

**Comment by JaydenDev** [comment]
go ahead and have it be merged to main since thats where the new searchbar functions are
testing doesnt work anyway

**Comment by hello-smile6** [comment]
> go ahead and have it be merged to main since thats where the new searchbar functions are testing doesnt work anyway

Okay.

**Comment by hello-smile6** [comment]
Ready to go!

**Comment by JaydenDev** [comment]
this PR breaks freecat

**Comment by JaydenDev** [comment]
you accidentally brought code from the broken testing branch, that's why. Get a clean slate (main branch) cloned and apply the stuffs.

**Comment by hello-smile6** [comment]
> you accidentally brought code from the broken testing branch, that's why. Get a clean slate (main branch) cloned and apply the stuffs.

Sorry.

**Comment by hello-smile6** [comment]
> you accidentally brought code from the broken testing branch, that's why. Get a clean slate (main branch) cloned and apply the stuffs.

Reviewed everything, it doesn't seem broken, but okay.

**Pull request merged**
