### PR TITLE
Update UI (Second PR)

### PR DESCRIPTION
**Pull request by hello-smile6**
Same as #104 , but different branch.

### CODE REVIEW

**Comment by hello-smile6** [comment]
@JaydenDev How's this?

**Comment by hello-smile6** [comment]
Ugh, error in build. Fixing.

**Comment by hello-smile6** [comment]
Nvm

**Comment by hello-smile6** [comment]
The testing branch got me.

**Comment by hello-smile6** [comment]
I fixed everything, it's ready now. I'll miss that baby so much...

**Comment by webdev03** [comment]
`npm run format`

**Comment by hello-smile6** [comment]
> `npm run format`

Okay

**Comment by hello-smile6** [comment]
@JaydenDev Are you going to merge?

**Comment by JaydenDev** [comment]
merging...

**Comment by JaydenDev** [comment]
idk white screen for some reason.

**Comment by JaydenDev** [comment]
@hello-smile6 white screen again

**Comment by JaydenDev** [comment]
> `npm run format`

prettier breaks FreeCat,  REMAKE YOUR PR AGAIN WITHOUT PRETTIER.

**Comment by JaydenDev** [comment]
How many times do I have to tell you. NO PRETTIER it broke FreeCat 3 times so far.

**Comment by JaydenDev** [comment]
prettier has been COMPLETELY removed from FreeCat, don't add it again. Remake your PR without prettier.

**Comment by hello-smile6** [comment]
Checking all commits for prettier check success. If any were successful, I'll redo those commits.

**Pull request merged**
