### PR TITLE
FreeCat Pre-Reset Fixed

### PR DESCRIPTION
**Pull request by hello-smile6**
If something doesn't work, tell me.
@JaydenDev

### CODE REVIEW

**Comment by hello-smile6** [comment]
@JaydenDev Don't merge quite yet.

**Comment by JaydenDev** [comment]
mark your PR as unfinished

**Comment by JaydenDev** [comment]
nuked is the wrong terminology
its a "reset" or "revert to 1.0" as it is

**Comment by JaydenDev** [comment]
btw #84

**Comment by hello-smile6** [comment]
> btw #84

It fixes that.

**Comment by JaydenDev** [comment]
The issue with freecat pre-reset
People were just making too many PRs without testing and confirming it works 100%. Adding too much bloat to manage. It was fine until I let ppl commit without PRs.

**Comment by hello-smile6** [comment]
> The issue with freecat pre-reset People were just making too many PRs without testing and confirming it works 100%. Adding too much bloat to manage. It was fine until I let ppl commit without PRs.

I'm almost done. Also, I've added some things, but don't worry. It's less than a kilobyte and I think you'll like it. See https://gist.github.com/hello-smile6/742d718eb19c60f0141d96c56a68fb90

**Comment by JaydenDev** [comment]
> > The issue with freecat pre-reset People were just making too many PRs without testing and confirming it works 100%. Adding too much bloat to manage. It was fine until I let ppl commit without PRs.
> 
> I'm almost done. Also, I've added some things, but don't worry. It's less than a kilobyte and I think you'll like it. See https://gist.github.com/hello-smile6/742d718eb19c60f0141d96c56a68fb90

so another new UI ok. Well make sure to make the CSS completely compatible and remove any unneeded CSS. Maybe let the user define what main style sheet they use in userchrome.css

**Comment by hello-smile6** [comment]
> > > The issue with freecat pre-reset People were just making too many PRs without testing and confirming it works 100%. Adding too much bloat to manage. It was fine until I let ppl commit without PRs.
> > 
> > 
> > I'm almost done. Also, I've added some things, but don't worry. It's less than a kilobyte and I think you'll like it. See https://gist.github.com/hello-smile6/742d718eb19c60f0141d96c56a68fb90
> 
> so another new UI ok. Well make sure to make the CSS completely compatible and remove any unneeded CSS. Maybe let the user define what main style sheet they use in userchrome.css

I used https://github.com/MystPi/dreamcss by @MystPi . :)

**Comment by JaydenDev** [comment]
> > > > The issue with freecat pre-reset People were just making too many PRs without testing and confirming it works 100%. Adding too much bloat to manage. It was fine until I let ppl commit without PRs.
> > > 
> > > 
> > > I'm almost done. Also, I've added some things, but don't worry. It's less than a kilobyte and I think you'll like it. See https://gist.github.com/hello-smile6/742d718eb19c60f0141d96c56a68fb90
> > 
> > 
> > so another new UI ok. Well make sure to make the CSS completely compatible and remove any unneeded CSS. Maybe let the user define what main style sheet they use in userchrome.css
> 
> I used https://github.com/MystPi/dreamcss by @MystPi . :)

is it the UI used in Ninetails, they specifically said to me to not copy their UI

**Comment by hello-smile6** [comment]
> > > > > The issue with freecat pre-reset People were just making too many PRs without testing and confirming it works 100%. Adding too much bloat to manage. It was fine until I let ppl commit without PRs.
> > > > 
> > > > 
> > > > I'm almost done. Also, I've added some things, but don't worry. It's less than a kilobyte and I think you'll like it. See https://gist.github.com/hello-smile6/742d718eb19c60f0141d96c56a68fb90
> > > 
> > > 
> > > so another new UI ok. Well make sure to make the CSS completely compatible and remove any unneeded CSS. Maybe let the user define what main style sheet they use in userchrome.css
> > 
> > 
> > I used https://github.com/MystPi/dreamcss by @MystPi . :)
> 
> is it the UI used in Ninetails, they specifically said to me to not copy their UI

No, it is not. It's a different stylesheet. I hope they don't mind it being used.

**Comment by hello-smile6** [comment]
@JaydenDev Just got a successful build, going to commit my changes. Then it should be ready to merge.

**Comment by kccuber-scratch** [comment]
Looking at the code it seems good

**Comment by hello-smile6** [comment]
Wait!

**Comment by hello-smile6** [comment]
I didn't add my changes yet!

**Comment by hello-smile6** [comment]
Continued in #92

**Pull request merged**
