### PR TITLE
add useragent

### PR DESCRIPTION
**Pull request by ScolderCreations**

### CODE REVIEW

**Comment by JaydenDev** [comment]
Have you tested your PR?

**Comment by JaydenDev** [comment]
i dont see why it wouldn't work, merging now

**Comment by MystPi** [comment]
Custom useragents mess up some sites, like Google. I suggest you remove it.

**Comment by hello-smile6** [comment]
> Custom useragents mess up some sites, like Google. I suggest you remove it.

I agree. Could you make a pr for that?

**Comment by MystPi** [comment]
> > Custom useragents mess up some sites, like Google. I suggest you remove it.
> 
> I agree. Could you make a pr for that?

Will do.

**Comment by MystPi** [comment]
Removed by #28.

**Pull request merged**
