### PR TITLE
Make URL bar show friendly homepage URL

### PR DESCRIPTION
**Pull request by hello-smile6**
This is #101 , but based on <a href="https://github.com/JaydenDev/freecat/tree/main">`main`</a>. @JaydenDev I wonder if it'd be possible to make the `freecat:` URL scheme this uses work globally, and maybe add a settings page using this.

### CODE REVIEW

**Comment by hello-smile6** [comment]
@JaydenDev I'm going to work on a settings page, think I figured it out.

**Comment by JaydenDev** [comment]
> @JaydenDev I'm going to work on a settings page, think I figured it out. It's going to build on this PR.

i need a 3 dots button implemented first.
plus i have that planned for 3.0
make tabs so i can release 2.0

**Comment by hello-smile6** [comment]
> > @JaydenDev I'm going to work on a settings page, think I figured it out. It's going to build on this PR.
> 
> i need a 3 dots button implemented first. plus i have that planned for 3.0 make tabs so i can release 2.0

I think tabs would take a lot of work, could I just do a menu? I could get that done easily. Otherwise, I'll probably end up copying everything from ninetails.

**Comment by hello-smile6** [comment]
Check Ninetails PR 49 :)

**Comment by hello-smile6** [comment]
@JaydenDev Could I do settings?

**Comment by hello-smile6** [comment]
@JaydenDev Let's make freecat automatically correct URLs for websites! For example, https://nodejs.com/ would go to https://nodejs.org/ and https://font-awesome.com/ would go to https://fontawesome.com/ ! Then people wouldn't waste time going to the wrong websites!

**Pull request merged**
