### PR TITLE
Unstable

### PR DESCRIPTION
**Pull request by hello-smile6**

### CODE REVIEW

**Comment by JaydenDev** [comment]
the whole reason I reverted to the latest commit of the add-icon branch was to fix freecat. Why add all the commits back to break it again?

**Comment by hello-smile6** [comment]
> the whole reason I reverted to the latest commit of the add-icon branch was to fix freecat. Why add all the commits back to break it again?

Because it might work.

**Comment by JaydenDev** [comment]
merge this into testing and i'll test it first.

**Comment by webdev03** [comment]
> merge this into testing and i'll test it first.

`gh pr checkout 81`

**Comment by hello-smile6** [comment]
> > merge this into testing and i'll test it first.
> 
> `gh pr checkout 81` can be used for checking out PRs too :D

Cool! https://cli.github.com/

**Pull request merged**
