### PR TITLE
Move code

### PR DESCRIPTION
**Pull request by webdev03**
Moves the package.json and package-lock to the root so that you can instantly run `npm install` and all npm commands as soon as you open your IDE/editor and also to enable automatic Prettier.

### CODE REVIEW

**Comment by JaydenDev** [comment]
conflicts

**Comment by webdev03** [comment]
Ah, there's a complex conflict now, can you just delete that app/package.json it might be easier?

**Comment by hello-smile6** [comment]
> Ah, there's a complex conflict now, can you just delete that app/package.json it might be easier?

On it.

**Comment by webdev03** [comment]
Wait,

**Comment by JaydenDev** [comment]
there is no need to open the files to /

**Comment by JaydenDev** [comment]
*move files to

**Comment by webdev03** [comment]
Ok

**Comment by webdev03** [comment]
I thought it would be good to make the Prettier work in VS Code that's why

**Comment by hello-smile6** [comment]
> there is no need to open the files to /

Actually, there is. Stop being so stubborn.

**Comment by webdev03** [comment]
I'm the one being stubborn, sorry

**Comment by JaydenDev** [comment]
how about all the code just be moved into the main directory I'm doing this right now.

**Comment by hello-smile6** [comment]
> how about all the code just be moved into the main directory I'm doing this right now.

That sounds good.

**Comment by webdev03** [comment]
That might clutter it up...

**Comment by hello-smile6** [comment]
> That might clutter it up...

But it'd make `npm install` easier.

**Comment by webdev03** [comment]
npm install already works with this PR

**Comment by JaydenDev** [comment]
it doesnt let me anyway

```
To https://github.com/JaydenDev/freecat
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/JaydenDev/freecat'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by webdev03** [comment]
@JaydenDev run `git pull` first

**Comment by JaydenDev** [comment]
didnt even let me run that
i'll just move the files

**Comment by JaydenDev** [comment]
i moved package.json and package-lock.json to /

**Comment by webdev03** [comment]
> i moved package.json and package-lock.json to /

You just broke it I think.

**Comment by webdev03** [comment]
@JaydenDev can you try to run Freecat with the current `main` branch?

**Comment by hello-smile6** [comment]
> @JaydenDev can you try to run Freecat with the current `main` branch?

Successful program execution on Windows 10.
```
Device name	localhost
Full device name	localhost
Processor	Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz   2.29 GHz  (2 processors)
Installed RAM	10.0 GB
Device ID	********-****-****-****-***********
Product ID	*****-*****-*****-*****
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```

**Comment by webdev03** [comment]
Doesn't work, did you pull the latest changes and are using JaydenDev/freecat

**Comment by hello-smile6** [comment]
> Doesn't work, did you pull the latest changes and are using JaydenDev/freecat

Merge my `main` branch, it works.
```
git pull https://github.com/hello-smile6/freecat.git
```

**Comment by webdev03** [comment]
:confused:

**Comment by hello-smile6** [comment]
#49 adds onto this PR.

**Pull request closed without merging**
