### PR TITLE
Use addEventListener, add CSP meta tag, complete HTML

### PR DESCRIPTION
**Pull request by hello-smile6**
I told you `addEventListener` was worth it!

### CODE REVIEW

**Comment by JaydenDev** [comment]
your PR has conflicts, please sort them out

**Comment by hello-smile6** [comment]
> your PR has conflicts, please sort them out

Okay.

**Comment by hello-smile6** [comment]
> your PR has conflicts, please sort them out

Done.

**Comment by JaydenDev** [comment]
i have a feeling your latest PR will break something...

**Comment by JaydenDev** [comment]
good nothing's broken

**Comment by hello-smile6** [comment]
> good nothing's broken

Screenshot?

**Pull request merged**
