### PR TITLE
Update prettier workflow to run on add-icon branch

### PR DESCRIPTION
**Pull request by hello-smile6**
I noticed that it wasn't running on #61 , so I thought of this.

### CODE REVIEW

**Comment by JaydenDev** [comment]
what did I say I dont need a branch for every release or feature, main should be the only branch.

**Comment by hello-smile6** [comment]
> what did I say I dont need a branch for every release or feature, main should be the only branch.

But a bunch of failed icon attempts will increase the size of releases.

**Comment by JaydenDev** [comment]
one branch, the constant channel IS the testing channel.

**Comment by hello-smile6** [comment]
> one branch, the constant channel IS the testing channel.

Okay, #60 would merge everything related to icons into the main branch.

**Pull request merged**
