### PR TITLE
Fix the semver thing again + other stuff (like prettier fix)

### PR DESCRIPTION
**Pull request by kccuber-scratch**
Reverting stuff broke this fix, so im adding it again

### CODE REVIEW

**Comment by hello-smile6** [comment]
@JaydenDev I know what needed fixed, could you undo the rollback?

**Comment by kccuber-scratch** [comment]
> @JaydenDev I know what needed fixed, could you undo the rollback?

No. I'm adding stuff in through this PR.

**Comment by hello-smile6** [comment]
> > @JaydenDev I know what needed fixed, could you undo the rollback?
> 
> No. I'm adding stuff in through this PR.

But I know what broke it and how to fix it.

**Comment by kccuber-scratch** [comment]
> > > @JaydenDev I know what needed fixed, could you undo the rollback?
> > 
> > 
> > No. I'm adding stuff in through this PR.
> 
> But I know what broke it and how to fix it.

ok, you can PR to the "semver-fix" branch on my fork and ill look at it

**Comment by hello-smile6** [comment]
> > > > @JaydenDev I know what needed fixed, could you undo the rollback?
> > > 
> > > 
> > > No. I'm adding stuff in through this PR.
> > 
> > 
> > But I know what broke it and how to fix it.
> 
> ok, you can PR to the "semver-fix" branch on my fork and ill look at it

I mean, the thing that made them do it.

**Comment by JaydenDev** [comment]
thankyou for backporting features

**Comment by hello-smile6** [comment]
> thankyou for backporting features

Could you create a branch that hasn't been nuked and let me try to fix it? I think I know how.

**Pull request merged**
