### PR TITLE
Add code of conduct

### PR DESCRIPTION
**Pull request by hello-smile6**

### CODE REVIEW

**Comment by JaydenDev** [comment]
the heck is this for

**Comment by JaydenDev** [comment]
This PR is not needed

**Comment by hello-smile6** [comment]
> This PR is not needed

It is.

**Comment by webdev03** [comment]
I'd prefer if there's a code of conduct

**Comment by hello-smile6** [comment]
> I'd prefer if there's a code of conduct

@JaydenDev @webdev03 Me too.

**Comment by webdev03** [comment]
Can you add this? It will give more trust and more people will contribute if they feel safe here.

**Comment by webdev03** [comment]
image
https://www.freecodecamp.org/news/how-to-contribute-to-open-source-projects-beginners-guide/

**Comment by webdev03** [comment]
Please?

**Comment by webdev03** [comment]
@JaydenDev ^

**Pull request closed without merging**
