### PR TITLE
global install file 

### PR DESCRIPTION
**Pull request by ScolderCreations**
this file prepares dependencies and opens the app. works on all major OSes, I think. Shouldn’t be too hard to test, just clone and run the shell script.

### CODE REVIEW

**Comment by FunctionalMetatable** [comment]
Windows? you should add batch as well

**Comment by JaydenDev** [comment]
its really not needed, they can just run those 3 commands.

**Comment by webdev03** [comment]
it is eslint, and also by the way who put eslint here? i didnt add my pr in

**Comment by webdev03** [comment]
**error  Expected '===' and instead saw '=='  eqeqeq**

**Comment by JaydenDev** [comment]
do we even need this PR? community, decide.

**Comment by hello-smile6** [comment]
> do we even need this PR? community, decide.

I vote yes.

**Comment by JaydenDev** [comment]
We don't need any useless bloat install scripts, when you git clone you are expected to be a developer. If you aren't a developer, grab a packaged build. EXE(s) will be provided for 1.1 along side linux packages.

**Comment by hello-smile6** [comment]
> We don't need any useless bloat install scripts, when you git clone you are expected to be a developer. If you aren't a developer, grab a packaged build. EXE(s) will be provided for 1.1 along side linux packages.

It's not useless _or_ bloat. Remember what you thought about using prettier? Remember when you didn't want to use `addEventListener`? This is a good idea!

**Comment by ScolderCreations** [comment]
> We don't need any useless bloat install scripts, when you git clone you are expected to be a developer. If you aren't a developer, grab a packaged build. EXE(s) will be provided for 1.1 along side linux packages.

This isn’t bloat, it’s just a time-saver.

**Comment by hello-smile6** [comment]
> > We don't need any useless bloat install scripts, when you git clone you are expected to be a developer. If you aren't a developer, grab a packaged build. EXE(s) will be provided for 1.1 along side linux packages.
> 
> This isn’t bloat, it’s just a time-saver.
> 
> If you don’t re-open this, don’t worry, I can make a new PR. There isn’t a reason not to have this, and there is a reason to have this, so I don’t get why you don’t want this. It’s entirely possible you just hate my code in general, but that isn’t very fair.

I'll reopen. Also, make the PR on my repo, so I can accidentally merge it the next time I sync my fork.

**Comment by hello-smile6** [comment]
Reopening. Please actually consider this this time.

**Comment by JaydenDev** [comment]
A time saver for 2 commands, lmao just type them yourself.

**Comment by hello-smile6** [comment]
> A time saver for 2 commands, lmao just type them yourself.

WHY? It's important!

**Comment by JaydenDev** [comment]
maybe ```npm run setup```
which runs
```bash
npm install
npm start
```

and

```bash
npm run linux64-install
```
which runs
```bash
echo Installing...
echo This script doesn't install native binary.
mkdir -p ~/.local/freecat
cp -r * ~/.local/freecat/
cat "npm start" >> freecat.bin
chmod +x freecat.bin
DIR=$(pwd)
ln -sf $DIR/freecat.bin ~/.local/bin/freecat
```

**Comment by hello-smile6** [comment]
> maybe `npm run setup` which runs
> 
> ```shell
> npm install
> npm start
> ```
> 
> and
> 
> ```shell
> npm run linux64-install
> ```
> 
> which runs
> 
> ```shell
> echo Installing...
> echo This script doesn't install native binary.
> mkdir -p ~/.local/freecat
> cp -r * ~/.local/freecat/
> cat "npm start" >> freecat.bin
> chmod +x freecat.bin
> DIR=$(pwd)
> ln -sf $DIR/freecat.bin ~/.local/bin/freecat
> ```

Huh.

**Comment by JaydenDev** [comment]
I used rather advanced bash programming...

pwd finds the current directory
cp coppies files
chmod +x marks a file as an executable
mkdir makes a directory.

**Comment by JaydenDev** [comment]
btw look at the PR number

**Comment by hello-smile6** [comment]
> btw look at the PR number

So?

**Comment by JaydenDev** [comment]
idk how to package.json so could you add my script under the respective commands

**Comment by hello-smile6** [comment]
> I don't know how to edit `package.json`, so could you add my script under the respective commands?

Sure.

**Comment by JaydenDev** [comment]
```bash
npm run linux64-run
npm run linux64-install
npm run deb64-make
npm run rpm64-make
```
I wanna have this kinda thing, so you don't end up having to make binaries for other platforms.

**Comment by JaydenDev** [comment]
> > ```shell
> > npm run linux64-run
> > npm run linux64-install
> > npm run deb64-make
> > npm run rpm64-make
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I wanna have this kinda thing, so you don't end up having to make binaries for other platforms.
> 
> That'd probably be easy. Just make it have individual scripts for each target and run all of them in the `make` script.

no.. no. the point of the individual scripts is to NOT build unnecessary binaries.

**Comment by hello-smile6** [comment]
> > > ```shell
> > > npm run linux64-run
> > > npm run linux64-install
> > > npm run deb64-make
> > > npm run rpm64-make
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I wanna have this kinda thing, so you don't end up having to make binaries for other platforms.
> > 
> > 
> > That'd probably be easy. Just make it have individual scripts for each target and run all of them in the `make` script.
> 
> no.. no. the point of the individual scripts is to NOT build unnecessary binaries.

Yes, you could then use the per-platform build scripts normally, but use the others when you have to build for a github release.

**Pull request merged**
