### PR TITLE
Add icon

### PR DESCRIPTION
**Pull request by hello-smile6**
Let's get this icon in! Merge subsequent PRs and commits into the `add-icon` branch. Don't merge until this works.
# Support

- [ ] Windows
- [ ] MacOS
- [ ] Linux

### CODE REVIEW

**Comment by webdev03** [comment]
Since we may be accepting PRs for this, I thought it might be good to label.

**Comment by hello-smile6** [comment]
> Since we may be accepting PRs for this, I thought it might be good to label.

Good idea, let's merge everything related to the icon into the `add-icon` branch.

**Comment by webdev03** [comment]
I'm working on getting it with Electron Forge. I'll add the file we're working on to make an icon, but which file are we using?

**Comment by JaydenDev** [comment]
k

**Comment by webdev03** [comment]
or the "big F"?

**Comment by JaydenDev** [comment]
seconds.svg at 32x32 sizse

**Comment by webdev03** [comment]
OK....

**Comment by JaydenDev** [comment]
you both have been removed from collaborators for abuse of permissions, and lacking of asking for permission. Its much safer if I have control of the flow and merging of repositories, so I can monitor and deny bad edits

**Comment by webdev03** [comment]
How did we abuse it?

**Comment by webdev03** [comment]
I did not accept it, I was waiting for you to give your permission, sorry. Unwanted changes? I thought we are working on this branch.

**Comment by JaydenDev** [comment]
Top contributors!?
we dont do that here.

**Comment by hello-smile6** [comment]
> you made unwanted changes to the README you almost accepted a concerning PR really? seriously?

Sorry, my display's only so big. And at the time when I said that it looked good, the readme hadn't been updated. I re-added the build link on theirs.

**Comment by JaydenDev** [comment]
re-added, learn from mistakes.

**Comment by JaydenDev** [comment]
icons are complicated

**Comment by webdev03** [comment]
`npm run format`

**Comment by hello-smile6** [comment]
> icons are complicated

Is it okay if I push a change that will get part of the way to having a Windows icon to the `add-icon` branch?

**Comment by webdev03** [comment]
Just a request if you can remove my logo and make a better one, mine was designed for macOS from the start.

**Comment by hello-smile6** [comment]
> Just a request if you can remove my logo and make a better one, mine was designed for macOS from the start.

I'll remove your logo from every commit. Okay?

**Comment by hello-smile6** [comment]
> > Just a request if you can remove my logo and make a better one, mine was designed for macOS from the start.
> 
> I'll remove your logo from every commit. Okay?

Never mind, but removing it from all branches.

**Comment by hello-smile6** [comment]
@JaydenDev You said you wanted to merge this into main. If you still want to, it's ready.

**Comment by JaydenDev** [comment]
Doesn't work on Linux

**Comment by hello-smile6** [comment]
> Doesn't work on Linux

Doesn't work on Windows, but you wanted to merge.

**Pull request merged**
