### PR TITLE
removed builds + added me as a contributor

### PR DESCRIPTION
**Pull request by ninjamar**
removed builds + added me as a contributor

sorry for spamming prs
solution : give me edit access

### CODE REVIEW

**Comment by ninjamar** [comment]
> By the way, can you format with prettier? Or I can do it for you.

How do I do that?

**Comment by webdev03** [comment]
I can do it.

**Comment by webdev03** [comment]
(it was literally a space, but whatever)

**Comment by ninjamar** [comment]
> (it was literally a space, but whatever)

ok
can you merge?

**Comment by hello-smile6** [comment]
> > (it was literally a space, but whatever)
> 
> ok can you merge?

Not yet, I want to review everything.

**Review by hello-smile6 — CHANGES_REQUESTED** [review]
Don't remove the build reference. There's no point in @JaydenDev having it if it's not used.

**Comment by webdev03** [comment]
Hey, this can get merged, but [this](https://github.com/marketplace/actions/auto-add-contributors) might work out better...

**Review by hello-smile6 — APPROVED** [review]
With the change I made, it's good to go.

**Comment by ninjamar** [comment]
someone added some `,` inside the file. can we remove them?

**Comment by hello-smile6** [comment]
> 

I agree, let's go with that.

**Review by webdev03 — APPROVED** [review]
Looks good!! (I don't know why I am doing this but OK!)

**Comment by ninjamar** [comment]
https://github.com/JaydenDev/freecat/pull/59/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R39
it should be "Better readme, random stuff and issues"

**Comment by JaydenDev** [comment]
dont give him edit access, only I can do that

**Comment by JaydenDev** [comment]
you do NOT use HTML in MARKDOWN
you CANT and SHOULDNT

Closing

**Comment by hello-smile6** [comment]
> you do NOT use HTML in MARKDOWN you CANT and SHOULDNT
> 
> Closing

You can use HTML in markdown, though.

**Comment by JaydenDev** [comment]
You CAN, I just hate it.

**Comment by webdev03** [comment]
Okay, sorry all, I think we now have a workflow that can add in the contributors for us :)

**Comment by ninjamar** [comment]
> Okay, sorry all, I think we now have a workflow that can add in the contributors for us :)

Ok. Why does @JaydenDev keep closing my issues and pr's?

**Comment by ninjamar** [comment]
> > > Okay, sorry all, I think we now have a workflow that can add in the contributors for us :)
> > 
> > 
> > Ok. Why does @JaydenDev keep closing my issues and pr's?
> 
> I think they just don't want help. Feel free to contribute to my fork.

Sure

**Comment by webdev03** [comment]
Yeah, I'm going on your fork now.

**Review by hello-smile6 — COMMENTED** [review]
No. Doesn't look good.

**Pull request closed without merging**
