### PR TITLE
Finish fixing up-to-date version

### PR DESCRIPTION
**Pull request by hello-smile6**
Continuing #91 .
I think I got everything, and I managed to build successfully.

### CODE REVIEW

**Comment by JaydenDev** [comment]
pr 91 already fixed everything
your PR will break things

**Comment by JaydenDev** [comment]
duplicate PR that does things that have already been done. useless.

**Comment by hello-smile6** [comment]
> duplicate PR that does things that have already been done. useless.

No, I didn't finish on #91. You merged it before I could finish. #91 leaved it in a partially fixed state.

**Comment by JaydenDev** [comment]
reopened for inspection
btw u already fixed it no need to do an unneeded fix sir

**Comment by JaydenDev** [comment]
its going into testing branch so ill accept it

**Comment by hello-smile6** [comment]
@JaydenDev I wasn't expecting you to merge it then. I didn't have time to finish. Also, I successfully built win32 binaries, you should be able to run them using `wine`.
https://instant.io/#c376dc9a9e8d869f3a4be999071f5e7433901aba

**Comment by hello-smile6** [comment]
> reopened for inspection btw u already fixed it no need to do an unneeded fix sir

I had fixed it, but didn't run `git commit` until after you merged.

**Comment by hello-smile6** [comment]
Does it work for you?

**Comment by hello-smile6** [comment]
@JaydenDev Does it work for you? Including releases?

**Comment by kccuber-scratch** [comment]
what the heck? why is it half under the GPL and half MIT? @JaydenDev dont tell me you merged PRs without looking again

**Comment by hello-smile6** [comment]
> what the heck? why is it half under the GPL and half MIT? @JaydenDev dont tell me you merged PRs without looking again

They're not merging without looking, obviously.

**Pull request merged**
