### PR TITLE
Better installation instructions

### PR DESCRIPTION
**Pull request by ninjamar**
I added better installation instructions because there doesn't need to be a separate file for every platform. 2 lines of shell script doesn't need its own file.

### CODE REVIEW

**Comment by webdev03** [comment]
`fakecommit` can just be an empty git commit probably with `git commit --allow-empty`. I hope this gets merged. Also run-mac.sh does nothing

**Comment by ninjamar** [comment]
> `fakecommit` can just be an empty git commit probably with `git commit --allow-empty`. I hope this gets merged. Also run-mac.sh does nothing

It shouldn't be based on platform, it should be based by shell.

**Comment by webdev03** [comment]
> > `fakecommit` can just be an empty git commit probably with `git commit --allow-empty`. I hope this gets merged. Also run-mac.sh does nothing
> 
> It shouldn't be based on platform, it should be based by shell.

Those scripts also have no reason to exist

**Comment by ninjamar** [comment]
> > > `fakecommit` can just be an empty git commit probably with `git commit --allow-empty`. I hope this gets merged. Also run-mac.sh does nothing
> > 
> > 
> > It shouldn't be based on platform, it should be based by shell.
> 
> Those scripts also have no reason to exist

Yep

**Comment by JaydenDev** [comment]
run-mac.sh doesn't have code in it since I don't know the utilities available in MacOS.

**Comment by webdev03** [comment]
It's the exact same as Linux, and anyways - there is no point of that, it is easy to say "just install dependencies and then `npm run start` to start developing"

**Comment by JaydenDev** [comment]
in MacOS since npm isn't installed via a package manager, I cant guarantee NPM is in the PATH

**Comment by webdev03** [comment]
NPM is installed either by downloading it through the node website (which should be in path already) or through a package manager like homebrew or through a version manager like NVM which also installs NPM.

**Comment by JaydenDev** [comment]
to make fc easier for new users the scripts are there

**Comment by webdev03** [comment]
But then if they know how to run those scripts they should be able to run 2 lines in the terminal?

**Comment by JaydenDev** [comment]
What's standard for my applications is a setup.bin, acting similarly to a Windows installer.
Using a Unix/Linux utility called: dialogue to create TUI menus for a proper installer. However, what's the point. We have packages, if you are a new user and cant code, install a package. The constant channel is for developers. Merging PR

**Comment by hello-smile6** [comment]
> What's standard for my applications is a setup.bin, acting similarly to a Windows installer. Using a Unix/Linux utility called: dialogue to create TUI menus for a proper installer. However, what's the point. We have packages, if you are a new user and cant code, install a package. The constant channel is for developers. Merging PR

I'll work on this. We need to allow everyone.

**Pull request merged**
