### PR TITLE
Disallow prettier using gitignore

### PR DESCRIPTION
**Pull request by hello-smile6**
I'll try to make a workflow which checks `package.json` for Prettier and fails if it finds it.

### CODE REVIEW

**Comment by JaydenDev** [comment]
Your PR will be reviewed over the next 24 hours.
Please continue to thoroughly test your code.

**Comment by JaydenDev** [comment]
> I'll try to make a workflow which checks `package.json` for Prettier and fails if it finds it.

this isn't needed
nobody will try to use it

however a workflow that checks for syntax errors, thats whats needed. eslint has an option to ONLY check syntax errors instead of styling which breaks everything

**Comment by JaydenDev** [comment]
> > I'll try to make a workflow which checks `package.json` for Prettier and fails if it finds it.
> 
> this isn't needed nobody will try to use it
> 
> however a workflow that checks for syntax errors, thats whats needed. eslint has an option to ONLY check syntax errors instead of styling which breaks everything

have eslint not auto fix errors, just LIST them in the PR comments

**Comment by hello-smile6** [comment]
> > > I'll try to make a workflow which checks `package.json` for Prettier and fails if it finds it.
> > 
> > 
> > this isn't needed nobody will try to use it
> > however a workflow that checks for syntax errors, thats whats needed. eslint has an option to ONLY check syntax errors instead of styling which breaks everything
> 
> have eslint not auto fix errors, just LIST them in the PR comments

Don't know how to do that.

**Comment by JaydenDev** [comment]
> > > > I'll try to make a workflow which checks `package.json` for Prettier and fails if it finds it.
> > > 
> > > 
> > > this isn't needed nobody will try to use it
> > > however a workflow that checks for syntax errors, thats whats needed. eslint has an option to ONLY check syntax errors instead of styling which breaks everything
> > 
> > have eslint not auto fix errors, just LIST them in the PR comments
> 
> Don't know how to do that.

Nobody needs eslint if you didn't break this so often

**Pull request closed without merging**
