### PR TITLE
Add build support (fix #6)

### LINKED ISSUE #6: Packaging with Electron Forge
```bash
npx electron-forge make --arch=64
```
returns
something about it not being able to find a makeable electron application

### PR DESCRIPTION
**Pull request by webdev03**
Fixed #6

### CODE REVIEW

**Comment by webdev03** [comment]
By the way, you need to `cd` into the app/ directory and then run `npm run make`

**Comment by JaydenDev** [comment]
Thanks!

**Comment by webdev03** [comment]
Okay, does it work?

**Comment by webdev03** [comment]
oops sorry double click 😞

**Pull request merged**
